version: '3'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: devlinks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  frontend:
    build:
      context: ./devlinks-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    # volumes:
    # - ./devlinks-frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # Useful for live reloading in Docker

  backend:
    build:
      context: ./devlinks-backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./devlinks-backend/.env  # Path to your .env file
    depends_on:
      postgres:
        condition: service_healthy

  migration:
    build:
      context: ./devlinks-backend
      dockerfile: Dockerfile.migrate
    env_file:
      - ./devlinks-backend/.env  # Path to your .env file
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
