version: '3'  

services:
  frontend:
    build:
      context: ./devlinks-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    # volumes:
      # - ./devlinks-frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # Useful for live reloading in Docker

  backend:
    build:
      context: ./devlinks-backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./devlinks-backend/.env  # Path to your .env file

  # Remove the mongo service if it's not needed
